global:
  name: Open Mainframe Project Interactive Landscape
  short_name: Open Mainframe Project
  repo: openmainframeproject/omp-landscape
  website: 'https://landscape.openmainframeproject.org'
  short_domain: l.openmainframeproject.org
  company_url: 'https://openmainframeproject.org'
  email: info@openmainframeproject.org
  meta:
    title: Open Mainframe Project Landscape
    fb_admin: alex.contini.94
    description: 'Filter and sort by GitHub stars, funding, commits, contributors, hq location, and tweets'
    twitter: '@OpenMFProject'
    google_site_verification: a2XVEjwm7VZNRuQ5wY3uDlwLXvxUzodGsIxwav3opvA
    ms_validate: 3AF9FFA12CCC3C49C0ABA71CCA222665
  membership: Open Mainframe Project Member Company
  flags:
    cncf_sandbox: false
    companies: Open Mainframe Project Member Company
twitter:
  search: landscape.openmainframeproject.org
  url: 'https://landscape.openmainframeproject.org'
  text: Open Mainframe Project Landscape from @OpenMFProject
relation:
  label: Open Mainframe Project Relation
  url: aswf
  values:
    - id: hosted
      label: Open Mainframe Project Projects
      children:
        - id: graduated
          label: Graduated Open Mainframe Projects
          prefix: OMP
          tag: Graduated
          color: '#3570af'
          big_picture_order: 1
          big_picture_label: OMP Graduated
          big_picture_color: 'rgb(24,54,114)'
        - id: incubating
          label: Incubating Open Mainframe Projects
          prefix: OMP
          tag: Incubating
          color: '#00cbff'
          big_picture_order: 2
          big_picture_label: OMP Incubating
          big_picture_color: 'rgb(83, 113, 189)'
    - id: company
      label: Open Mainframe Project Members
      tag: Company
      big_picture_order: 3
    - id: member
      label: Open Mainframe Project Member Products/Projects
      tag: Open Mainframe Project Member
    - id: false
      label: Non-Open Mainframe Project Member Products/Projects
      url: 'no'
membership:
  Platinum:
    name: Open Mainframe Project
    label: Platinum Member
    funding: Platinum
  Silver:
    name: Open Mainframe Project
    label: Silver Member
    funding: Silver
  Academic Institution:
    name: Open Mainframe Project
    label: Academic Institution Member
    funding: Academic Institution
  Associate:
    name: Open Mainframe Project
    label: Associate Member
    funding: Associate
  'false':
    funding: 'No'
home:
  header: >
    <h1>Open Mainframe Project Interactive Landscape</h1> The Open Mainframe Project landscape (<a target="_blank" href="images/landscape.png">png</a>, <a target="_blank"
    href="images/landscape.pdf">pdf</a>) is dynamically generated below. It is modeled after the <a href="http://landscape.cncf.io">CNCF landscape</a> and based
    on the same open source code.
  footer: |
    Crunchbase data is used under license from Crunchbase to CNCF.
ads:
  - url: 'https://events.linuxfoundation.org/events/kubecon-cloudnativecon-north-america-2019/?utm_source=lfdl_landscape&utm_medium=web&utm_campaign=kccncna19'
    image: /images/info1.jpg
  - url: 'https://events.linuxfoundation.org/events/kubecon-cloudnativecon-europe-2020/?utm_source=cncf_landscape&utm_medium=web&utm_campaign=kccnceu20'
    image: /images/info2.jpg
presets:
  - url: /category=open-mainframe-project-member-company&format=card-mode&grouping=category
    label: Open Mainframe Project members
  - url: /category=zowe-conformant&format=card-mode&grouping=category
    label: Zowe Conformant offerings
  - url: /format=card-mode&grouping=no&license=open-source&sort=first-commit
    label: Open source cards by age
  - url: /format=card-mode&grouping=category
    label: Cards in categories
  - url: /format=card-mode&grouping=no&sort=stars
    label: Cards by stars
  - url: /format=card-mode&grouping=headquarters
    label: Group by location
big_picture:
  main:
    tab_index: -1
    url: landscape
    name: Landscape
    title: Open Mainframe Project Landscape
    fullscreen_header: See the interactive landscape at l.openmainframeproject.org
    method: getGroupedItemsForCncfBigPicture
    size:
      width: 1155
      height: 740
    fullscreen_size:
      width: 1155
      height: 740
    elements:
      - type: HorizontalCategory
        category: Projects
        rows: 3
        width: 700
        height: 200
        top: 0
        left: 0
        color: 'rgb(78,171,207)'
        fit_width: true
      - type: HorizontalCategory
        category: Zowe Conformant
        rows: 3
        width: 700
        height: 160
        top: 395
        left: 0
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: HorizontalCategory
        category: Linux Distributions
        rows: 3
        width: 300
        height: 160
        top: 215
        left: 0
        color: 'rgb(64, 89, 163)'
        fit_width: true
      - type: HorizontalCategory
        category: Supported Projects
        rows: 3
        width: 380
        height: 160
        top: 215
        left: 320
        color: 'rgb(74, 131, 104)'
        fit_width: true
      - type: HorizontalCategory
        category: Open Mainframe Project Member Company
        rows: 6
        width: 1000
        height: 300
        top: 570
        left: 0
        color: 'rgb(124, 200, 182)'
        fit_width: true
      - type: LandscapeInfo
        width: 365
        height: 200
        top: 0
        left: 740
        children:
          - type: text
            text: >
              This landscape is intended as a map to explore open source projects within the mainframe industry,
              and also shows the member companies of the Open Mainframe Project.
            top: 45
            left: 100
            right: 120
            font_size: 10
          - type: image
            image: qr.svg
            top: 40
            left: 5
            width: 90
            height: 90
          - type: title
            title: l.openmainframeproject.org
            top: 129
            left: 9
            font_size: 12
          - type: image
            image: left-logo.svg
            width: 110
            right: 5
            top: 45
          - type: image
            image: right-logo.svg
            width: 109
            right: 5
            top: 85
test:
  header: Open Mainframe Project Interactive Landscape
  section: Graduated Open Mainframe Projects
  logo: zowe.svg
update_server:
  ip: 147.75.106.211
  update_hour: 0
  update_minute: 0
